<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>LiteExcel.Demo</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LiteExcel.Demo</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LiteExcel\LiteExcel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Data" />
  </ItemGroup>

</Project>
